twig:
    default_path: '%kernel.project_dir%/templates'
    debug: true
    cache: false
    auto_reload: true
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
