vich_uploader:
    db_driver: orm

    mappings:
        faculty_images:
            uri_prefix: '%app.path.faculty_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.faculty_images%'
        student_images:
            uri_prefix: '%app.path.student_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.student_images%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
